Create bare-bones library
ros2-rust/ament_cargo_plugin pull request #1
Opened 2020-12-02 16:47 UTC by jhdcs

Created the bare-bones library. I apologize for the lengthy copyright notice, but it's a requirement from my work that I have to put it on all files I create.

Distro A, OPSEC #4584

Signed-off-by: Jacob Hassold <jhassold@dcscorp.com>

2020-12-03 08:44 UTC, bergercookie approved these changes

2020-12-03 09:47 UTC, esteve requested changes

2020-12-03 09:47 UTC, esteve commented on ament_cargo/src/lib.rs
> +// Copyright 2020 DCS Corporation, All Rights Reserved.
I understand that this is your employer, but I don't agree with adding their copyright here, given that this is a community project. Is there a formula in which you can add yourself as a contributor instead? Otherwise we can add a generic copyright (e.g. the ros2-rust developers) and list your employer in a separate file.

2020-12-04 14:01 UTC, jhdcs commented on ament_cargo/src/lib.rs
> +// Copyright 2020 DCS Corporation, All Rights Reserved.
Thank you for your response!

According to the ROS 2 developer guide (https://index.ros.org/doc/ros2/Contributing/Developer-Guide/), under the section "Documentation", there is a rule that "Each source file must have a license and copyright statement, checked with an automated linter." The ROS 2 projects that I've seen follow this guidance for source files (https://github.com/ros2/rclcpp/blob/master/rclcpp/src/rclcpp/any_executable.cpp), though they relax the rules somewhat for CMakeLists and the like. In my view, the `.toml` file is somewhat analogous to the CMakeLists file (_veeeeeeeeery_ somewhat), so I didn't put the notice on it. The `lib.rs` file is a source file, so I put the notice there.

One of the problems we run into, though, is that in the United States (and some other countries) copyright is implied upon file creation. Meaning that if I create a file, the copyright is created then and there. Line 1 of the `lib.rs` file is technically just a notice.

Additionally, if we were to do a group/generic copyright as done in the [cartographer project](https://github.com/cartographer-project/cartographer/blob/master/AUTHORS), I'm sure that we would have to get our lawyers involved to create a document that would stand up to legal scrutiny. And any future corporations/contributors would have to abide by or amend some sort of agreement before getting added in...

If your concern is that we might take back the file at some point in the future, rest assured we cannot. The Apache License applies to all code that's put in the file, and we cannot remove it for an already existing document, nor its derivatives.

2020-12-06 17:15 UTC, esteve commented on ament_cargo/src/lib.rs
> +// Copyright 2020 DCS Corporation, All Rights Reserved.
I've been member of the Apache Software Foundation for more than 10 years and one of the original authors of ROS 2, so I'm quite familiar with both ;-)

> I'm sure that we would have to get our lawyers involved

Who is **we** in this case?

Anyway, the cartographer project was founded by Google, and I'm quite sure their legal department knows what they are doing with the Apache license, so I definitely trust that if they can do a group copyright, so can we.

According to your rationale, if someone else were to create that file, you wouldn't have to add your employer's notice, is that correct? If so, I can create the file and assign the copyright to the collective.

2020-12-07 13:48 UTC, jhdcs commented on ament_cargo/src/lib.rs
> +// Copyright 2020 DCS Corporation, All Rights Reserved.
Spoke a bit more with my superiors, and it seems that a group copyright like you're suggesting will work for us. We just ask that the OPSEC and "Delivered to" sections of the header are included for our entry. If that's doable?

2020-12-08 12:30 UTC, bergercookie approved these changes

2020-12-15 12:15 UTC, jhdcs commented
@esteve, will these changes work?

2020-12-22 17:59 UTC, esteve commented
@jhdcs sorry for the slow response, I missed your latest changes. Yeah, they look good, that way we don't have to worry about adding the DCS appendix to every file. However, out of curiosity, if you contribute to an existing file, does that appendix still need to be added? e.g. you submit a PR to `rclcpp`, does that appendix have to be added to `rclcpp.hpp`? To be honest, it's the first time I see one of those.

2020-12-22 20:31 UTC, jhdcs commented
> if you contribute to an existing file, does that appendix still need to be added? e.g. you submit a PR to `rclcpp`, does that appendix have to be added to `rclcpp.hpp`?

No, I don't have to. It's only for new files that are created by me.

2020-12-22 20:32 UTC, merged